### ISSUE TITLE
PACKAGES.rds manifest contains only one package

### ISSUE THREAD

**Issue by vspinu** [ursa-labs/arrow-r-nightly#18]
PACKAGES.rds does not contain paths to all packages available in the repository:

```R
url <- "https://arrow-r-nightly.s3.amazonaws.com/src/contrib/PACKAGES.rds"
destfile <- tempfile(fileext = ".rds")
download.file(url, destfile = destfile)
packages <- as.data.frame(readRDS(destfile), stringsAsFactors = FALSE)
str(packages)
## 'data.frame':	1 obs. of  15 variables:
##  $ Package              : chr "arrow"
##  $ Version              : chr "6.0.0.20211103"
##  $ Priority             : chr NA
##  $ Depends              : chr "R (>= 3.3)"
##  $ Imports              : chr "assertthat, bit64 (>= 0.9-7), methods, purrr, R6, rlang,\nstats, tidyselect, utils, vctrs"
##  $ LinkingTo            : chr NA
##  $ Suggests             : chr "DBI, dbplyr, decor, distro, dplyr, duckdb (>= 0.2.8), hms,\nknitr, lubridate, pkgload, reticulate, rmarkdown, s"| __truncated__
##  $ Enhances             : chr NA
##  $ License              : chr "Apache License (>= 2.0)"
##  $ License_is_FOSS      : chr NA
##  $ License_restricts_use: chr NA
##  $ OS_type              : chr NA
##  $ Archs                : chr NA
##  $ MD5sum               : chr "d3e9bf5346733faaa9698cb6665f2cde"
##  $ NeedsCompilation     : chr "yes"
```

This makes it difficult to install older packages from the archive. Most specifically with renv. 

Full details of issue: https://github.com/rstudio/renv/issues/848
Diagnosed in [this comment](https://github.com/rstudio/renv/issues/848#issuecomment-959673000)

**Comment by kevinushey** [comment]
Here:

https://github.com/ursa-labs/arrow-r-nightly/blob/b4ff0d1b398cbddb97d11de1968b77f47537e99a/build-binary-and-upload.R#L28

I believe you can pass `latestOnly = FALSE` to instruct R to generate PACKAGES entries for all versions of the package available in the repository.

**Comment by nealrichardson** [comment]
Hmm. I suspect that won't work because the older versions of the package are already in S3, not in the current working dir. Any suggestions for how to construct it? Can we treat the PACKAGES files like something we can append to, so maybe download the current PACKAGES, append the new one, then produce the .gz and .rds versions from that?

**Comment by kevinushey** [comment]
I believe `tools:::update_PACKAGES()` is designed for that scenario.

**Comment by assignUser** [comment]
@vspinu We now have [nightlies.apache.org/arrow/r](https://nightlies.apache.org/arrow/r) which keeps up to 14 versions around. We do advice against using the nightly builds in production/something like renv though, as we are deleting old version. If you want to use the nightly builds regardless you should back them up somewhere.

**Comment by nealrichardson** [comment]
@assignUser is right, we are moving (have moved) this project to nightlies.apache.org. I'm going to close this issue now; any further issues about arrow nightly packages should go to https://issues.apache.org/jira/projects/ARROW/issues.
